---
- name: Configure CentOS 7.x VM with GNOME for OPS445 labs
  hosts: hliu232
  user: student
  become: yes
  vars:
    user_name: "hliu232"
    lab_dirs:
      - lab1
      - lab2
      - lab3
      - lab4
      - lab5
      - lab6
      - lab7
      - lab8

  tasks:
    - name: Update Apache
      yum:
        name: httpd
        state: latest

    - name: Install extra packages repository
      yum:
        name: epel-release
        state: present

    - name: Remove 'tree' package
      yum:
        name: tree
        state: absent

    - name: Set the hostname to hliu232
      hostname:
        name: "{{ user_name }}"

    - name: Create a new user hliu232
      user:
        name: "{{ user_name }}"
        state: present
        create_home: yes
        shell: /bin/bash

    - name: Add hliu232 to sudoers and access without a password
      lineinfile:
        path: /etc/sudoers
        line: "{{ user_name }} ALL=(ALL) NOPASSWD:ALL"
        state: present
        validate: '/usr/sbin/visudo -cf %s'

    - name: allow new user to SSH login without a password
      authorized_key:
        user: "{{ user_name }}"
        state: present
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

    - name: Set up directories for organizing labs
      file:
        path: "/home/{{ user_name }}/ops445/{{ item }}"
        state: directory
        owner: "{{ user_name }}"
        group: "{{ user_name }}"
      loop: "{{ lab_dirs }}"

